import React from "react";
import styled from "styled-components"
import { Wrapper } from "../wrapper/Wrapper";

interface ThreeOptionSectionProps { }

const ThreeOptionSectionComponent = styled.div`
display: flex;
align-items: center;
background-color: #eff6fa;
width: 100%;
height: 40vh;
`;

const Content = styled.div`
display: flex;
align-items: center;
justify-content: space-between;
`;

const Option = styled.div`
text-align: center;
width: 30%;
`;

const Heading = styled.div`
font-family: galanogrotesque-s;
margin-top: 20px;
margin-bottom: 10px;
`;

const Desc = styled.div`
font-family: galanogrotesque-r;
font-size: 15px;
`;

export const ThreeOptionSection: React.FC<ThreeOptionSectionProps> = () => {
    return (
        <ThreeOptionSectionComponent>
            <Wrapper>
                <Content>
                    <Option>
                        <img src="assets/icons/search.svg" alt="" />
                        <Heading>Search</Heading>
                        <Desc>
                        {" Simply add a keyword or a term related to your business "}
                        {" in the slogan maker search box. Wait for the magic to happen. "}
                        </Desc>
                    </Option>
                    <Option>
                        <img src="assets/icons/select.svg" alt="" />
                        <Heading>Select</Heading>
                        <Desc>
                        {" Choose from thousands of options generated by the  "}
                        {" slogan maker that fit your needs. "}
                        </Desc>
                    </Option>
                    <Option>
                        <img src="assets/icons/stand.svg" alt="" />
                        <Heading>Stand out</Heading>
                        <Desc>
                        {" Congrats on your new slogan. It's time to win the world! "}
                        </Desc>
                    </Option>
                </Content>
            </Wrapper>
        </ThreeOptionSectionComponent>
    )
}